version: "3.9"

services:
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_INTERVAL=10
      - AUTOHEAL_START_PERIOD=60
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD-SHELL", "docker ps | grep autoheal || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
