services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      - /srv/core:/srv
      - /srv/core/filebrowser.db:/database/filebrowser.db
    environment:
      - FB_BASEURL=/
    restart: unless-stopped
