services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Los_Angeles
      - N8N_HOST=nxcore.aerovista.local
      - N8N_PROTOCOL=http
    volumes:
      - /srv/core/n8n_data:/home/node/.n8n
    restart: unless-stopped
