[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.10"
strict = false
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
disallow_untyped_defs = true
exclude = ["\.venv/"]

[tool.ruff]
line-length = 100
target-version = "py310"
extend-select = ["I"]
exclude = [".venv"]