version: "3.9"

networks:
  gateway:
    external: true

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER=status=running
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - gateway
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`logs.nxcore.tail79107c.ts.net`)
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.routers.dozzle.tls=true
# - traefik.http.routers.dozzle.middlewares=authelia@docker
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3

