version: "3.9"

networks:
  gateway:
    external: true

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    command: >
      -H unix:///var/run/docker.sock
      --http-disabled
      --tlsskipverify
    ports:
      - "9444:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - gateway
      - default
    labels:
      - traefik.enable=false  # Using path-based routing instead
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:9443/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  portainer_data:

