# Updated Traefik Static Configuration
# Include TLS configuration for custom certificates

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  api:
    address: ":8083"

providers:
  docker:
    exposedByDefault: false
    network: gateway
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: true
  insecure: false

log:
  level: INFO

accessLog: {}

# TLS Configuration
tls:
  certificates:
    - certFile: /certs/fullchain.pem
      keyFile: /certs/privkey.pem
      stores:
        - default

  options:
    default:
      minVersion: VersionTLS12
      maxVersion: VersionTLS13
      sniStrict: true
      alpnProtocols:
        - http/1.1
        - h2
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

    # WebSocket-friendly configuration
    websocket:
      minVersion: VersionTLS12
      maxVersion: VersionTLS13
      sniStrict: true
      alpnProtocols:
        - http/1.1
