global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'nxcore'
    environment: 'production'

# Alertmanager configuration (optional - add later)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          node: 'nxcore'
          role: 'core'

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          node: 'nxcore'

  # Blackbox Exporter (endpoint probes)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://nxcore.tail79107c.ts.net/
          - https://traefik.nxcore.tail79107c.ts.net/
          - https://auth.nxcore.tail79107c.ts.net/
          - https://n8n.nxcore.tail79107c.ts.net/
          - https://files.nxcore.tail79107c.ts.net/
          - https://portainer.nxcore.tail79107c.ts.net/
          - https://grafana.nxcore.tail79107c.ts.net/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # PostgreSQL Exporter (database metrics - add later)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis Exporter (cache metrics - add later)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Traefik metrics (if enabled)
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
        labels:
          service: 'traefik'

