services:
  meshcentral:
    image: ghcr.io/ylianst/meshcentral:latest
    ports: ["4430:443","4433:4433"]
    volumes: ["./meshcentral-data:/meshcentral-data"]
    restart: unless-stopped
  rustdesk-hbbs:
    image: rustdesk/rustdesk-server:latest
    command: hbbs -k _
    ports: ["21115:21115","21116:21116","21116:21116/udp","21118:21118","21114:21114"]
    volumes: ["./rustdesk-data:/root"]
    restart: unless-stopped
  rustdesk-hbbr:
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    network_mode: "service:rustdesk-hbbs"
    depends_on: ["rustdesk-hbbs"]
    restart: unless-stopped
  syncthing:
    image: syncthing/syncthing:latest
    hostname: fleet-sync
    environment: ["PUID=1000","PGID=1000","TZ=America/Los_Angeles"]
    ports: ["8384:8384","22000:22000/tcp","22000:22000/udp","21027:21027/udp"]
    volumes: ["./syncthing-data:/var/syncthing"]
    restart: unless-stopped
  dashboard:
    image: nginx:alpine
    ports: ["8090:80"]
    volumes: ["./dashboard:/usr/share/nginx/html:ro"]
    restart: unless-stopped
